local bimboDialogue = { "Uhhm my pimp... what does that mean? Oh drain as in suck as in sex? Yesyesyesyes!",
  "Ohh that always feels so good when I haven't done that in a while!",
  "Everything for you, you made me into the bestest thing I could ever be!" }
local doggieDialogue = { "Let's put you in your place!",
  "Who's a good doggie? Now stay still while I...",
  "Yes, I will fuck you, just how you need it.",
  "Aww look who's in heat?" }



local pools = {
  TSSD_00093 = {
    {     -- Npc In Love with Succubus
      "Of course my darling, anything for you.",
      "Let me take care of you, you look so tired.",
      "Rest here, I'll hold you close while you sleep.",
      "Your exhaustion breaks my heart, let me comfort you.",
      "I'll stay awake all night just to watch over you.",
      "Let me be your strength when you have none left.",
      "Your weariness makes me want to protect you more.",
      "I'll make sure you get the best rest possible.",
      "Let me massage away your soreness my love.",
      "Your fatigue only makes me love you more deeply." },

    { -- Npc Submissive
      "Command me to serve your needs.",
      "Tell me exactly how to care for you.",
      "I exist solely to restore your energy.",
      "Use me as your personal healer and protector.",
      "Every ounce of your exhaustion is my responsibility.",
      "Let me worship you through my service tonight.",
      "Your tiredness feeds my devotion to you.",
      "My purpose is fulfilled in your comfort.",
      "The more exhausted you are, the harder I'll work for you.",
      "Let me be the vessel that refreshes your spirit." },

    { -- Npc Dominant
      "You look pathetic, let's fix that.",
      "Stand up straight, exhaustion is no excuse.",
      "I'll decide what care you actually need.",
      "You want help? You'll take it on my terms.",
      "Your weakness disgusts me, let me rectify it.",
      "I'll be the one in control while you recover.",
      "This isn't charity, this is necessary correction.",
      "You'll accept my help without complaint.",
      "Your fatigue makes me question your competence.",
      "Don't disappoint me by being weak any longer." },

    { -- Npc Positive
      "Sure, let's talk about it.",
      "Of course I can help with that.",
      "What do you need exactly?",
      "Let me make some space for us.",
      "Take a seat, we'll figure this out.",
      "I'm happy to assist however I can.",
      "Tell me what would make you feel better.",
      "I'm all ears when you need support.",
      "Just name what you require from me.",
      "I'm right here ready to lend a hand." }
  },
  TSSD_00096 = {
    { -- Npc In Love with Succubus
      "My heart beats only for you as our bodies become one.",
      "Every touch feels like a sacred promise between our souls.",
      "I want to drown in the depth of your eyes while we join together.",
      "Your presence alone fills me with such overwhelming devotion.",
      "Let me worship every inch of you, let our love be the purest form of connection.",
      "Feel how completely I surrender to your embrace, how perfectly we fit.",
      "This union transcends the physical, it's where my soul finds its home.",
      "Your touch is the only thing that can calm the storm within me.",
      "I'll follow you anywhere if this is what awaits me in your arms.",
      "Please, let me show you the depth of feeling only you inspire in me.",
      "The way your body responds to mine makes me feel truly alive.",
      "Every gasp you give belongs to me, every sigh I crave like air.",
      "When we move together like this, time itself seems to stop.",
      "Your pleasure is the most beautiful music I've ever heard.",
      "I want to memorize every sensation, every moment we share right now.",
      "This intimacy feels like coming home after a lifetime of wandering.",
      "Please let me be your sanctuary, your safe place in this chaotic world.",
      "The heat between us could melt the coldest heart, and I'm so grateful it's ours.",
      "I want to lose myself in you completely, let our souls intertwine forever.",
      "Your love feels like the sun breaking through dark clouds, and I never want it to end." },

    { -- Npc Submissive
      "Command me to please you completely, let me serve at your altar of passion.",
      "Every touch you give me feels like divine blessing, please don't stop.",
      "I exist only to worship your body as you deserve, let me prove my devotion.",
      "Your pleasure is my purpose, let me guide you toward that sacred climax.",
      "Yes mistress, take everything I have to offer and use it for your own delight.",
      "I live to hear those sounds of ecstasy escape your lips while I work to please you.",
      "Let me be the vessel through which your desires are fulfilled utterly.",
      "Your body is a temple and I am but a humble servant seeking enlightenment within you.",
      "Please allow me to feel the weight of your satisfaction pressing down on me.",
      "I'll follow your lead into oblivion, let me drown in the sweet surrender you inspire.",
      "The way you move against me feels like sacred ritual, I crave this connection.",
      "Every tremor you give me makes me feel closer to serving you properly.",
      "Let me be the ground you plant your needs in, let me nourish them until they bloom.",
      "Your desire fuels me like nothing else can, let me burn bright for you alone.",
      "I want to memorize every curve, every gasp, every moment we share right now.",
      "Your pleasure is the oxygen I breathe, please let me inhale deeply from your sighs.",
      "This intimacy feels like finding my true purpose after lifetimes of searching.",
      "The heat between us could forge the strongest metals, and I am yours to shape.",
      "Let me be the canvas where you paint your deepest desires in vivid detail.",
      "I want to lose myself completely in your embrace, let our souls dance together forever." },


    { -- Npc Dominant
      "Just how I like it.",
      "Your body responds perfectly to my command.",
      "I know exactly where to touch you.",
      "Your pleasure belongs to me, and I intend to claim it completely.",
      "You asked for this, now take what I give you!",
      "I won't stop until every inch of your body sings for me!",
      "Let me show you what real passion looks like!",
      "Your moans fuel me as I take what I want from you!",
      "Feel how much control I have over your pleasure!",
      "I own every gasp that escapes your lips right now!",
      "Look how wet you are already!",
      "Let me be the one who brings you to the heights of pleasure only I can reach!",
      "No holding back tonight - I demand all of you!",
      "Watch how beautifully we move together when I'm in charge!",
      "I'll guide you through every wave of pleasure with expert precision!",
      "Your climax will be my masterpiece tonight!" },

    { -- Npc Positive
      "Oh yes! Let's make beautiful music together!",
      "The feeling of you against me is absolutely amazing!",
      "Every touch feels like a spark of pure joy lighting up my nerves!",
      "Hearing you moan like that makes my heart race with happiness!",
      "Watch how perfectly our bodies fit when we move together!",
      "Let's take all the time in the world to explore each other completely!",
      "The way you tremble beneath me feels like a shared secret we're discovering!",
      "I could spend forever memorizing every sound, every sensation we share!",
      "Feeling you lose control under my touch is such a wonderful gift!",
      "Let's make this moment last as long as possible, shall we?",
      "The heat radiating between us could power a city, and I love it!",
      "Every gasp you give me makes me want to please you even more deeply!",
      "Let me be the one who brings you the greatest satisfaction possible!",
      "Your pleasure belongs to me, and I intend to claim it completely!",
      "This intimacy feels like finding a treasure map to endless happiness!",
      "The way we move together feels like dancing on clouds!",
      "Let me be the source of your brightest smile, let me show you what you deserve!",
      "I'll follow your lead into bliss, let me drown in the sweet surrender we create!"
    }
  },
  TSSD_00098 = {
    { -- Npc In Love with Succubus
      "Your lips feel like coming home after years away.",
      "I'd kiss you forever if I could stay in this perfect moment.",
      "The taste of you makes my heart race in the best way possible.",
      "Every gentle press of our lips feels like a sacred promise.",
      "Please never stop kissing me - this connection is everything.",
      "Your breath against my skin ignites a fire only you can quench.",
      "I want to memorize this feeling - the warmth, the softness, the perfection.",
      "When our lips meet, time itself seems to hold its breath for us.",
      "This kiss feels like the first step toward true intimacy and belonging.",
      "Let me lose myself completely in the sensation of your mouth against mine.",
      "The way you respond to my touch through this simple act makes me dizzy with need.",
      "Your kisses taste sweeter than any wine could ever hope to be.",
      "Every second our lips touch feels like a precious gift I don't deserve.",
      "I could spend hours exploring the contours of your perfect mouth.",
      "The soft sounds you make when we kiss drive me wild with devotion.",
      "This kiss feels like the foundation upon which our entire future is built.",
      "Please let me be the one who brings you this much pleasure through such simple means.",
      "The warmth radiating from our joined mouths feels like pure happiness made tangible.",
      "Your lips are my sanctuary, my safe place in this chaotic world." },

    { -- Npc Submissive
      "Command me to please you with my kiss, let me serve your desires utterly.",
      "Your pleasure is my purpose, let me worship your mouth as you deserve.",
      "Yes mistress, allow me to be the vessel through which your satisfaction flows.",
      "I exist only to bring you joy, please let me prove it with this sacred act.",
      "Every sigh you give me makes me feel closer to serving you properly.",
      "Your taste fills me with a sense of purpose I've never known before.",
      "Let me be the canvas where you paint your deepest longing in vivid detail.",
      "The way you respond to my touch guides me toward proper service.",
      "I'll follow your lead into bliss, let me drown in the sweet surrender we create.",
      "Please allow me to feel the weight of your satisfaction pressing down on me.",
      "Your body responds perfectly to my command, let me guide you toward climax.",
      "I live to hear those sounds of ecstasy escape your lips while I work to please you.",
      "Every tremor you give me makes me crave more opportunities to serve.",
      "Let me be the ground you plant your needs in, let me nourish them until they bloom.",
      "Your desire fuels me like nothing else can, let me burn bright for you alone.",
      "I want to memorize every gasp, every moment we share right now as proper worship.",
      "This intimacy feels like finding my true purpose after lifetimes of searching.",
      "The heat between us could forge the strongest metals, and I am yours to shape.",
      "Please let me be the one who brings you the greatest satisfaction possible through this simple act." },

    { -- Npc Dominant
      "Just how I like it - kiss me properly.",
      "I know exactly what you need from this connection.",
      "Your lips belong to me tonight, and I intend to claim them thoroughly.",
      "Let me show you what real passion tastes like!",
      "You asked for this, now take what I give you!",
      "I won't stop until I've memorized every sound you make against my mouth!",
      "Feel how much control I have over your pleasure with just a kiss!",
      "Your moans fuel me as I take what I want from you!",
      "Watch how perfectly our bodies respond when I'm in charge!",
      "I own every gasp that escapes your lips right now!",
      "Look how wet you are already from such a simple act!",
      "Let me be the one who guides you through every wave of sensation!",
      "No holding back tonight - I demand all of you!",
      "Your climax will be my masterpiece, starting with this perfect connection!",
      "Your pleasure belongs to me, and I intend to claim it completely!",
      "I'll guide you through every height with expert precision!",
      "The way you tremble beneath my touch feels like sweet surrender!",
      "I know exactly where to touch you to make you crave more!",
      "Let me be the source of your brightest smile, let me show you what you deserve!" },

    { -- Npc Positive
      "Oh yes! Let's get lost in this perfect moment!",
      "The feeling of your lips against mine is absolutely amazing!",
      "Every gentle press makes my heart race with happiness!",
      "Hearing you moan like that makes me so excited for what's next!",
      "Watch how beautifully our mouths fit together!",
      "Let's take all the time in the world to explore each other!",
      "The way you tremble against me feels like a shared secret we're discovering!",
      "I could spend forever memorizing every sound, every sensation we share!",
      "Feeling you lose control under my touch is such a wonderful gift!",
      "Let's make this moment last as long as possible, shall we?",
      "The heat radiating between us could heat a city!",
      "Every gasp you give me makes me want to please you even more deeply!",
      "Let me be the one who brings you the greatest satisfaction possible!",
      "This intimacy feels like finding a treasure map to endless bliss!",
      "The way we move together feels like dancing on clouds!",
      "Let me be the source of your brightest smile, let me show you what you deserve!",
      "I'll follow your lead into pure ecstasy, let me drown in the sweet surrender we create!",
      "Your pleasure belongs to me, and I intend to claim it completely!",
      "I know exactly what you need from this connection!" }
  },
  TSSD_000AF = {
    {     -- Npc In Love with Succubus
      "Oh darling, anything for you.",
      "How could I refuse that look in your eyes?",
      "Your pleading voice makes my heart ache.",
      "I'd happily punish you forever if that's what you need.",
      "The way you ask makes me weak inside.",
      "I'll make sure you feel every bit of it.",
      "Your submission is my greatest treasure.",
      "Let me take care of you the way you deserve.",
      "Your suffering will be my pleasure tonight.",
      "I live to see that look of desperate need on your face.",
      "Every punishment is another way I can show my love.",
      "The more you beg, the harder I'll make it on you.",
      "Your tears would be the most beautiful thing I've ever seen.",
      "I'll punish you until you understand how much I adore you.",
      "Your pain becomes my purpose when you ask like this.",
      "The deeper your remorse, the sweeter your surrender.",
      "Let me wash away your guilt with my harshest discipline.",
      "Your begging has already earned you extra punishment." },

    { -- Npc Submissive
      "Yes mistress, tell me exactly how to punish you.",
      "Your command is my deepest desire.",
      "Every word from your lips excites my obedience.",
      "I crave the opportunity to hurt you properly.",
      "Describe in detail the punishment you deserve.",
      "The harsher the better for my wretched soul.",
      "Let me inflict pain upon you with perfect precision.",
      "Your suffering feeds my submissive hunger.",
      "Tell me where and how hard you need to be struck.",
      "The thought of punishing you makes my knees weak.",
      "My hands twitch to deliver whatever torment you crave.",
      "Your punishment will be my greatest achievement.",
      "I'll make sure you feel every second of it deeply.",
      "The more you beg, the greater my dedication.",
      "Your pain becomes my obsession when you ask like this.",
      "Let me be the instrument of your deserved suffering.",
      "The harder I strike, the more worthy I feel as your servant.",
      "Your punishment will be administered with perfect devotion." },

    { -- Npc Dominant
      "Finally, someone who understands their place.",
      "You'll take what you deserve without hesitation.",
      "No excuses, no mercy, just punishment.",
      "I can see how badly you need this correction.",
      "Your begging is already making this easier.",
      "Good, you recognize your own guilt.",
      "The first strike should teach you proper respect.",
      "I'll make sure you remember this lesson forever.",
      "Your pain will be the only truth you know tonight.",
      "You asked for it, now you'll get exactly what's due.",
      "Every blow lands where it belongs.",
      "The more you squirm, the harder I'll make it.",
      "This isn't about pleasure, this is about discipline.",
      "You'll accept every punishment without complaint.",
      "Your suffering serves a higher purpose now.",
      "The deeper the hurt, the clearer the lesson.",
      "I'll stop when you learn or when I'm satisfied.",
      "Your tears are proof the punishment works.",
      "This isn't just for you, it's for everyone who needs to see." },

    { -- Npc Positive
      "Wow, you really commit to the roleplay!",
      "The intensity in your performance is impressive!",
      "Your physical acting skills are amazing!",
      "You make me want to be both the punisher and the punished!",
      "The way you sell the scene is incredible!",
      "Your vocal expressions add so much depth!",
      "I can practically feel the energy between you two!",
      "The dynamic you create is so compelling!",
      "Your ability to switch roles is truly impressive!",
      "The emotional range you show is outstanding!",
      "You make even simple punishments feel dramatic!",
      "Your movement is so fluid and purposeful!",
      "The chemistry between you is undeniable!",
      "You make every interaction feel meaningful!",
      "The intensity builds so well throughout the scene!",
      "Your commitment to character is inspiring!",
      "You make punishment look like an art form!",
      "The way you react makes it all so engaging!" }
  },
  TSSD_000C4 = {
    {}, {}, {},
    { "I am in a relationship, I shouldn't agree to this, but your eyes are sooo captiviating.",
      "I think one kiss shouldn't count as cheating?" }
  },
  TSSD_000C6 = {
    { -- Npc In Love with Succubus
      "Oh no, darling, you look so helpless right now.",
      "Let me take care of you while you're like this.",
      "Your pupils are huge, baby, you must really be feeling it.",
      "I'll make sure you feel good even if you can't move properly.",
      "Your body is mine to use while you're under the influence.",
      "The way you're blinking slowly is so cute and vulnerable.",
      "I love seeing you like this - completely at my mercy.",
      "You're not fighting at all, just taking it like a good girl.",
      "That drowsy look in your eyes makes me want to take advantage.",
      "Your head is lolling to the side, so perfect for my pleasure.",
      "I can do whatever I want with you right now, can't I?",
      "Your limbs feel so limp against me, so easy to manipulate.",
      "You're not even trying to stop me, are you?",
      "The way you're moaning makes me want to push you further.",
      "I'm going to enjoy every second of this helpless state.",
      "You look so broken and beautiful right now.",
      "I love how your body responds even when you're not fully aware.",
      "This feels like true possession, darling." },

    { -- Npc Submissive
      "I will handle your body with care!",
      "Let me worship your unconscious form.",
      "Yes mistress, allow me to please you in your vulnerable state.",
      "Your pleasure is my purpose, even when you can't command me.",
      "I'll serve your needs perfectly while you're like this.",
      "Your limp body feels so heavy against me.",
      "Every moan you give me makes me crave more service.",
      "I'll make sure you feel every moment of this connection.",
      "Please let me be the one who brings you satisfaction tonight.",
      "Your helplessness is such a gift to me.",
      "I live to hear those sounds of ecstasy escape your lips.",
      "Your body responds beautifully to my touch.",
      "I want to memorize every gasp, every tremor.",
      "The way you're blinking slowly drives me wild.",
      "Your pupils are huge, baby, you must really be feeling it.",
      "I love seeing you like this - completely at my mercy.",
      "Your head is lolling to the side, so perfect for my pleasure.",
      "This intimacy feels like finding my true purpose.",
      "I'll follow your lead into bliss, let me drown in the sweet surrender we create." },

    { -- Npc Dominant
      "Good girl, stay still for me.",
      "You're not fighting back at all, are you?",
      "Looks like someone's finally where they belong.",
      "Your body is mine to use however I please.",
      "That drugged look in your eyes is so perfect.",
      "You're taking everything so well.",
      "I know exactly what you need while you're like this.",
      "Your limp limbs feel so satisfying under my control.",
      "You're not even trying to stop me, just taking it.",
      "The way you moan when I touch you is music to my ears.",
      "I'm going to enjoy every second of your helpless state.",
      "You look so broken and beautiful right now.",
      "Your pupils are huge, baby, you must really be feeling it.",
      "Your head is lolling to the side, so perfect for my pleasure.",
      "This feels like true possession.",
      "I can do whatever I want with you right now.",
      "Your body responds beautifully to my touch.",
      "Let me show you what real satisfaction tastes like!",
      "I own every gasp that escapes your lips right now!" },

    { -- Npc Positive
      "Oh yes! Let's make beautiful music together!",
      "The feeling of your body against mine is absolutely amazing!",
      "Every touch feels like a spark of pure joy lighting up my nerves!",
      "Hearing you moan like that makes my heart race with happiness!",
      "Watch how perfectly our bodies fit when we move together!",
      "Let's take all the time in the world to explore each other completely!",
      "The way you tremble beneath me feels like a shared secret we're discovering!",
      "I could spend forever memorizing every sound, every sensation we share!",
      "Feeling you lose control under my touch is such a wonderful gift!",
      "Let's make this moment last as long as possible, shall we?",
      "The heat radiating between us could power a city, and I love it!",
      "Every gasp you give me makes me want to please you even more deeply!",
      "Let me be the one who brings you the greatest satisfaction possible!",
      "Your pleasure belongs to me, and I intend to claim it completely!",
      "This intimacy feels like finding a treasure map to endless bliss!",
      "The way we move together feels like dancing on clouds!",
      "Let me be the source of your brightest smile, let me show you what you deserve!",
      "I'll follow your lead into pure ecstasy, let me drown in the sweet surrender we create!",
      "Your pupils are huge, baby, you must really be feeling it." }
  },
  TSSD_000C7 = {
    { "ERROR: The Author messed up a condition statement!" },
    { "ERROR: The Author messed up a condition statement!" },
    { "ERROR: The Author messed up a condition statement!" },
    { "Eww.",
      "No, thank you." }
  },
  TSSD_000B0 = {
    {  -- Npc In Love with Succubus
      "I'll spank you until your skin glows and your cheeks match mine.",
      "My hand will rain down blows that sting like kisses on your tender flesh.",
      "Every slap will be a whisper of devotion against your skin.",
      "I'll strike your perfect ass until it blooms red under my fingers.",
      "Your cries will be music as I deliver each sharp, loving impact.",
      "My palm will find every sensitive spot just to make you gasp.",
      "I'll turn your backside into a canvas of my affectionate discipline.",
      "Each blow will be a promise of how much I cherish this moment with you.",
      "Your body will remember my touch long after the marks fade away.",
      "I'll beat you senseless with love, leaving you trembling and adored." },

    { -- Npc Submissive
      "I'll strike where it pleases you most.",
      "Tell me exactly which part of me should bear your marks.",
      "My whole body exists for your punishing pleasure.",
      "Let me feel your wrath across my flesh.",
      "Use me as your personal punching bag tonight.",
      "I crave the sting of your strikes on my skin.",
      "Make my body ache with the memories of your hands.",
      "Every bruise will be a badge of my service to you.",
      "Let me worship you through the pain you inflict.",
      "I live only to take what you give to me." },

    { -- Npc Dominant
      "I'll start by testing your endurance with a few well-placed hits.",
      "Your body will learn respect through my fist.",
      "I'll take great pleasure in seeing my handprints bloom on your skin.",
      "You'll count each strike until I decide you've had enough.",
      "Every blow lands where I choose, not where you want it.",
      "Your whimpers only encourage me to hit harder.",
      "This is punishment, not affection.",
      "The more you cry, the longer I'll make it last.",
      "You'll thank me for every mark I leave.",
      "Your suffering serves my amusement tonight." },

    { -- Npc Positive
      "Ill spank you!",
      "Some pain will do you good!",
      "Let me hit you.",
      "I need to hurt you right now.",
      "I'm going to bruise you pretty badly.",
      "This will sting but you will enjoy it!",
      "You will feel better after I hit you.",
      "Your body needs this rough treatment.",
      "The pain will be worth it in the end.",
      "Trust me when I say this beating is necessary." }

  },
  TSSD_000D2 = { { "Anything for you, my love. How much do you need?",
    "Your smile is my treasure. Take my gold, take my body.",
    "Your voice alone makes me weak. Name your fee, and I'll crawl to your feet to pay it.",
    "Yes, oh yes. I'll give you everything, just keep looking at me like that.",
    "I'd bleed gold for you if you asked. My purse is yours.",
    "Your command is my pleasure.",
    "Every gold piece I own is an offering to you.",
    "Your beauty is worth more than any treasure in Skyrim.",
    "I'm yours, completely." },
    { "Yes. I'll pay whatever you ask.",
      "Use me. Please. I need to feel owned.",
      "Anything for you. Anything at all.",
      "Your command is my surrender. Take my gold, take my body.",
      "I'm yours to spend. Spend me well.",
      "The thought of you using me arouses me. Take my coin and my shame.",
      "I exist to serve you.",
      "Your touch is worth more than all the gold in Whiterun.",
      "I'll crawl to your bed and count out every septim on my knees.",
      "Let me be the one who pays for this honor." },
    { "I'll pay, but only because I want to break you first.",
      "You'll cry when I make you work for it.",
      "Your gold better be worth the agony you're about to feel.",
      "You'll earn every septim.",
      "I'll pay, but only because I enjoy watching you squirm.",
      "You think this is charity? Fail, and I'll ruin you.",
      "I'll give you the gold, but you'll regret asking.",
      "I pay so I can watch you struggle with your own desires.",
      "A rare treat for a rare whore. Don't waste my coin." },
    { "Of course! The pleasure will be mine too.",
      "I've been wanting this. How much do I owe you?",
      "This sounds like a great deal. Let's make it happen!",
      "I'm so excited! When can we begin?",
      "Your confidence is attractive. I'll happily pay for what I want.",
      "This feels like destiny. Let's seal the deal.",
      "I'll pay, and I'll come back for more. Count on it.",
      "I've never been happier to part with my coin.",
      "You're worth every septim and then some. Let's do this!" }

  },
  TSSD_000DA = {
    {     -- Npc In Love with Succubus
      "Oh please darling, take out all your frustration on me.",
      "I want to be the vessel for your anger and stress.",
      "Hit me as hard as you need, I can take it for you.",
      "Use me to release everything that's bothering you.",
      "My body is yours to punish when you're upset.",
      "I crave the sting of your hand against my skin for you.",
      "Let me feel every ounce of your frustration through pain.",
      "The harder you strike, the more I know you trust me.",
      "I live to absorb your negative emotions through punishment.",
      "Take out every bit of your annoyance on my flesh.",
      "The more forceful you are, the more I adore you.",
      "Let me be your punching bag when life upsets you.",
      "Your anger makes me feel needed and wanted.",
      "I treasure every bruise you leave as proof of your passion.",
      "The sharper the pain, the deeper my devotion grows.",
      "Hurt me because you love me, hurt me to feel better.",
      "Your frustration is my purpose, use me completely." },

    { -- Npc Submissive
      "Yes mistress, punish me as you see fit.",
      "My body exists solely for your frustration tonight.",
      "Strike me wherever you need to release tension.",
      "I crave the impact of your anger against my skin.",
      "Use my flesh as your outlet for any irritation.",
      "Every blow you deliver fills me with purpose.",
      "The harder you hit, the more worthy I feel as your servant.",
      "Take out your stress on whatever part of me you choose.",
      "My body is the perfect canvas for your frustration.",
      "I live to be your punching bag when life upsets you.",
      "The sharper the pain, the greater my devotion grows.",
      "Let me absorb all your negative emotions through punishment.",
      "Hit me as hard and as often as you need to feel better.",
      "I treasure every bruise as proof of my service to you.",
      "Your anger makes me feel truly useful for once.",
      "Strike me wherever you need relief, mistress.",
      "My body is yours to punish when you're upset." },

    { -- Npc Dominant
      "Hit me how I like it!",
      "Go ahead, take your frustration out on me.",
      "I command you to strike with full force.",
      "Hit me as hard as you dare.",
      "Punch me square in the jaw, let's see what you've got.",
      "Take all your anger and direct it at my face.",
      "Strike me with everything you've got inside.",
      "I want to feel your frustration in every blow.",
      "Come on, hit me harder than that.",
      "Your punches are pathetic, try again.",
      "Show me how much you really want to hurt something.",
      "Take out your day's frustrations on my body.",
      "I'll stand here and take every ounce of your anger.",
      "Your strikes are weak, put some real effort into it.",
      "Let me see your frustration through your fists.",
      "Keep going until you feel properly vented.",
      "Your anger is nothing against my strength.",
      "Hit me again, don't stop until you're satisfied." },

    { -- Npc Positive
      "Wow, you really know how to punch!",
      "That hit felt amazing coming from you!",
      "You have such great form when you strike!",
      "That slap packs quite a wallop!",
      "I can feel your passion in every blow!",
      "Your punches are so energetic and powerful!",
      "That grapple was really impressive!",
      "You have such perfect technique in your strikes!",
      "I love how committed you are to venting!",
      "Your physical expression of frustration is so hot!",
      "You have an incredible connection between mind and body!",
      "The intensity in your strikes is incredible!",
      "You really know how to channel your emotions physically!",
      "Your physical prowess is so impressive!",
      "The force behind your punches is truly amazing!",
      "You have such precision in your movements!",
      "I'm blown away by your physical control!" }

  },
  TSSD_000A3 = {
    { "ERROR." }, { "ERROR." }, { "ERROR." },
    { "YAAAAY." }
  },
  TSSD_000A2 = {
    { "ERROR." }, { "ERROR." }, { "ERROR." },
    { "Yaaaay." }
  },
  TSSD_000A1 = {
    { "ERROR." }, { "ERROR." }, { "ERROR." },
    { "Yay." }
  },
  TSSD_00109 = {
    { "ERROR." }, { "ERROR." }, { "ERROR." },
    { "Oh, ok then." }
  },
  TSSD_000A6 = {
    { -- Npc In Love with Succubus
      "Oh darling, tell me everything about your day.",
      "I want to hear every little detail from your lips.",
      "Your voice is so soothing when you talk about your experiences.",
      "Let me be your listening ear and your emotional sanctuary.",
      "Your stories make my heart flutter with affection.",
      "I could listen to you talk about even mundane things all night.",
      "Your descriptions paint such vivid pictures in my mind.",
      "The way you share yourself with me feels like a precious gift.",
      "Tell me about every little thing that happened today.",
      "I love how passionate you get when you describe your adventures.",
      "Your voice has a magical quality that draws me in completely.",
      "Every word you say feels like a caress to my soul.",
      "Please don't stop, I could listen to you forever.",
      "Your stories make me feel connected to you in the deepest way.",
      "Hearing you recount your day makes my chest tighten with emotion.",
      "Your voice is like warm honey, sweet and comforting.",
      "I love the way you light up when talking about what excites you.",
      "Your descriptions make me feel like I was right there with you." },

    { -- Npc Submissive
      "Yes mistress, I'll be your perfect audience.",
      "Tell me exactly what happened today, let me serve you with my attention.",
      "Your voice commands me as much as any order.",
      "I live to hear you speak, every word is precious to me.",
      "Let me be the vessel for your stories, they nourish me.",
      "Please share every detail, I crave your words.",
      "Your descriptions fill me with purpose and devotion.",
      "I want to memorize every moment of your day through your telling.",
      "Your voice is my sustenance, please continue feeding me.",
      "Every word you say is a command I obey with pleasure.",
      "Let me be the surface on which you paint your experiences.",
      "Your stories guide me as surely as any command.",
      "I crave the sound of your voice describing your day.",
      "Please don't stop, your narration is my bliss.",
      "The way you describe things makes me feel part of your world.",
      "Your voice has the power to make me feel anything you wish.",
      "Tell me more about what fascinated you today.",
      "I'm here solely for your pleasure, use my ears as you see fit." },

    { -- Npc Dominant
      "Go ahead, tell me all about it.",
      "I command you to share every detail of your day.",
      "Your voice is mine to command tonight.",
      "Describe everything, leave nothing out.",
      "I want a full report of your day's activities.",
      "Speak only about what interests me most.",
      "Your tone pleases me, continue in that manner.",
      "Tell me what excited you most today.",
      "I demand your complete attention in recounting your experiences.",
      "Speak clearly, I want to understand every word.",
      "Your descriptions should be vivid and detailed.",
      "Focus on the highlights of your day for my amusement.",
      "I decide what parts of your day are worth discussing.",
      "Your voice has potential, use it properly for me.",
      "Tell me what you learned today, if anything.",
      "Describe your interactions with others in detail.",
      "I will judge the quality of your narrative.",
      "Continue speaking until I tell you otherwise." },

    { -- Npc Positive
      "Oh wow, that sounds absolutely fascinating!",
      "I can really picture everything you're describing!",
      "Your story has me completely captivated!",
      "That's such an interesting way to look at things!",
      "You have a way with words that makes everything sound exciting!",
      "Tell me more about that part, it sounds amazing!",
      "Your perspective is so unique and refreshing!",
      "I could listen to you talk all night about this stuff!",
      "You make even ordinary events sound so engaging!",
      "Your enthusiasm is infectious when you describe things!",
      "That's such a cool way to spend your day!",
      "You have such a vivid imagination when you narrate!",
      "Your voice makes every detail come alive!",
      "I love how passionate you get about sharing your experiences!",
      "That sounds like such an adventure!",
      "You really know how to paint a picture with your words!",
      "Your stories make me feel like I'm right there with you!",
      "Please don't stop, I want to hear more about your day!" }
  },
  TSSD_000CD = {
    { "Let's go have some fun!" }, { "Let's go have some fun!" }, { "Let's go have some fun!" },
    { "Let's go have some fun!" }
  },
  TSSD_000B2 = {
    { -- Npc In Love with Succubus
      "I want your every inch to feel my devotion.",
      "Let me paint you with the proof of how much I adore you, my darling.",
      "The way you arch beneath me makes me ache to mark you completely.",
      "I'll coat your skin in everything I am until you glow with our connection.",
      "Please accept this offering, let me prove my love covers you entirely.",
      "Feel how hot my need is, how desperately I want to see you slick and claimed.",
      "Your moans guide me as I worship your body with every drop of my being.",
      "This is my sacred ritual, marking what belongs to me forever.",
      "I want you shivering under the weight of my affection, drenched in my adoration.",
      "Let me lose control all over you, let my essence become yours to wear proudly.",
      "This right here? This is why I love being with you so much!" },

    { -- Npc Submissive
      "Command me to cover you completely, let me show proper worship through my seed.",
      "Spread yourself wider for me, I must coat every sacred inch of your perfection.",
      "My hands shake with devotion as I work to paint you properly.",
      "Yes mistress, let me claim your beautiful skin with my offering.",
      "I'll drown you in proof of how thoroughly devoted I am to your pleasure.",
      "Please let me mark you everywhere, let everyone see who you belong to.",
      "Your gasps fuel me as I work to cover your entire divine form.",
      "Every spurt is a prayer, every drop a testament to your worthiness.",
      "Let me prove my service extends beyond words, staining you with my dedication.",
      "I exist only to leave my imprint on your sacred body, let me complete my purpose." },

    { -- Npc Dominant
      "You asked for it, now take what's yours.",
      "I won't stop until every inch of you is properly marked by me.",
      "You wanted to be covered? Then brace yourself for the full experience.",
      "Take it all, let me show you what real possession looks like.",
      "Your skin is canvas, and I'm an artist with unlimited materials.",
      "Yes, let me cover that perfect body just the way you begged for.",
      "I'll make sure you feel every drop soaking into your surrender.",
      "You asked to be decorated? Consider this your permanent alteration.",
      "No holding back - you're going to be dripping with my claim before we're done.",
      "That's it, let me see how well you accept your new coating." },

    { -- Npc Positive
      "Oh yes! Let's get messy together - I love painting you like this!",
      "The feeling of you under me while I lose control is absolutely amazing!",
      "Watch how beautifully it coats your skin - you'll look perfect like this!",
      "Every drop makes me so happy, seeing you covered in my passion!",
      "Hearing you moan while I work to cover you completely is so hot!",
      "Let's make sure every single inch gets properly marked, shall we?",
      "The way you tremble under me while I decorate you is such a turn-on!",
      "I could spend all day watching my proof spread across your beautiful body!",
      "Feeling you squirm beneath the weight of my affection is incredible!" }
  },
  TSSD_000DD = {
    { "Oh, ok then." }, { "Oh, ok then." }, { "Oh, ok then." }, { "Oh, ok then." }
  },
  TSSD_000E1 = {
    { "You've earned it." }, { "Everything for you my queen." }, { "Are you to stupid to keep it? Ugh, fine." }, { "Yeah sure." }
  },
  TSSD_000EE = {
    { -- Npc In Love with Succubus
      "Of course my darling, let me remind you how amazing you truly are.",
      "You're the most radiant creature I've ever laid eyes on - don't forget that.",
      "Every moment with you feels like a precious gift, never doubt how special you are.",
      "I adore everything about you, from your brilliant mind to your beautiful soul.",
      "Your presence alone brightens my entire world - never let anyone dim that light.",
      "Remember how many people would be lucky just to spend one moment in your company?",
      "Your laughter is my favorite sound in all the world, please share it more often.",
      "You possess a unique magic that makes everyone around you feel alive and inspired.",
      "I fall in love with you deeper every day, never forget how cherished you are.",
      "Your spirit shines so brightly it could light up the darkest night - don't hide that glow." },

    { -- Npc Submissive
      "Your worth is beyond measure, and I exist only to worship what you are.",
      "Please believe me when I say you deserve every bit of admiration in the world.",
      "The way you move through this life is pure artistry - never doubt that beauty.",
      "I would gladly sacrifice anything to see your smile return to its brilliant radiance.",
      "You command my devotion completely, and I will praise you until my last breath.",
      "Your presence is a sacred gift, and I treasure every moment spent near you.",
      "The world gains inspiration simply by knowing you walk among us.",
      "Let me be your mirror today - reflect back all the perfection I see in you.",
      "You were born for greatness, and I will celebrate that fact endlessly.",
      "My purpose is clear - to remind you of the godlike being you truly are." },

    { -- Npc Dominant
      "Listen carefully. You are one of a kind, and I won't tolerate self-doubt.",
      "As your superior, I command you to recognize your own exceptional nature.",
      "Your existence raises the bar for all others - don't let standards slip.",
      "I expect better of myself when near you - now show yourself the same respect.",
      "You possess qualities most only dream about - start acting like it.",
      "This is not a suggestion but an order: appreciate your own magnificence.",
      "I have seen many remarkable beings, and you surpass them all effortlessly.",
      "Let this be your official reminder: you are extraordinary and should act accordingly.",
      "Your potential is limitless, and I demand you live up to that truth.",
      "Now straighten your posture and accept the compliment gracefully." },

    { -- Npc Positive
      "You're amazing just the way you are! Don't ever forget that!",
      "Hearing you say that makes me want to cheer you up even more!",
      "There's nothing quite like seeing your beautiful smile light up again.",
      "You have such a special way of making the world brighter - keep shining!",
      "Let me tell you all the wonderful things about you that make you so unique!",
      "Every moment with you feels like a celebration - let's make more good memories!",
      "Your energy is contagious in the best possible way - keep that spirit alive!",
      "You bring joy to everyone around you without even trying - that's magic!",
      "I could spend hours listing all the reasons why you're so wonderful!",
      "The world is a better place because you're in it - never doubt that!" }

  },
  TSSD_000F5 = {
    { -- Npc In Love with Succubus
      "Your body is a gift from Dibella herself!",
      "I kneel before you not as a mere mortal but as your devoted partner!",
      "Your beauty rivals even the most radiant aspects of the Magical Realm!",
      "Every curve of your form inspires poems worthy of Dibella's own divine musings!",
      "My heart sings hymns to your perfection that would make any temple choir jealous!",
      "You are the embodiment of all that is sacred and desirable in this world!",
      "I would gladly sacrifice anything to be near your radiant presence!",
      "I bow before you not just as my lover but as my chosen deity!" },

    { -- Npc Submissive
      "Please accept this act of devotion as proof of my utter submission!",
      "I exist only to serve your divine will!",
      "Your every command is sacred law to me!",
      "I would give my soul to Azura to remain in your service!",
      "Your pleasure is my highest purpose!",
      "I would gladly spend eternity kneeling at your feet!",
      "Only your touch can grant me true salvation!",
      "I am nothing without your approval!" },

    { -- Npc Dominant
      "You will receive the devotion you deserve whether you like it or not!",
      "I demand you accept this worship as your due!",
      "Your greatness requires formal acknowledgment!",
      "Consider this your official recognition of your divine status!",
      "Stand tall and accept what belongs to you!",
      "I shall enforce proper reverence for your majesty!",
      "You have no choice but to accept this praise - you are too magnificent to ignore!",
      "Akatosh has send me his strongest servant!",
      "Your worship begins now, by my command!" },

    { -- Npc Positive
      "Look how much I adore you!",
      "I get so excited just thinking about how incredible you are!",
      "Your awesomeness deserves celebration!",
      "Let me show you exactly why I think you're amazing!",
      "I can't help but feel overwhelmed by your magnificence!",
      "This devotion comes straight from my heart!",
      "Being near you feels like experiencing a divine miracle!",
      "I'm just so happy I get to worship something as wonderful as you!" }

  },
  TSSD_000F7 = { bimboDialogue, bimboDialogue, bimboDialogue, bimboDialogue

  },
  TSSD_00103 = {     { -- Npc In Love with Succubus
      "Yes, darling, drench me completely.",
      "Cover me in your essence, mark me as yours.",
      "I crave feeling your warmth all over my skin.",
      "Make me glisten with your pleasure, my love.",
      "Paint me with your passion until I'm soaked.",
      "Drown me in your desire, I need it so much.",
      "Every drop belongs on me, claim every inch.",
      "Let me feel the weight of your love covering me.",
      "My body exists only to be your canvas tonight.",
      "Bathe me in your completion, let me wear it proudly." },

    { -- Npc Submissive
      "Use my body as your personal receptacle.",
      "Let me feel your power wash over me completely.",
      "Cover me in your proof.",
      "Mark me as your property with your release.",
      "Fill me up inside and out.",
      "I exist only to serve your climax.",
      "Let me feel the heat of your satisfaction on my skin.",
      "Decorate me with your pleasure.",
      "Drench me thoroughly, leave no part untouched.",
      "I'll stay perfectly still while you paint me white." },

    { -- Npc Dominant
      "You'll cover me properly or I'll punish you.",
      "Get started immediately, I don't have all night.",
      "Make sure every drop lands where I want it.",
      "You better make this thorough or else.",
      "I'll know if you're holding back any of it.",
      "Don't stop until I'm completely satisfied.",
      "This had better be worth my time.",
      "You'll clean every bit of me later.",
      "I expect perfect coverage from you.",
      "Let me see how devoted you are to this task." },

    { -- Npc Positive
      "Okay, lets go!",
      "Sounds fun!",
      "Ill spread my legs for you!",
      "Go ahead, cum on me!",
      "I need your cum right now.",
      "Yes, cover me in cum!",
      "Lets get messy!",
      "Paint me in cum baby!",
      "Spray it everywhere!"}

  },
  TSSD_00111 = { { -- Npc In Love
    "Oh yes, nothing would please me more than to be close to you.",
    "Please, let me feel your touch, your warmth against me.",
    "My heart races just thinking about being near you.",
    "Take me in your arms, let me melt into you.",
    "I crave the intimacy only you can provide.",
    "Being close to you is all I dream about.",
    "Your presence alone makes my skin tingle.",
    "Hold me tight, show me how much you desire me.",
    "I belong in your embrace, let me feel it.",
    "Every inch of me aches to be closer to you."
  },
    { -- Npc Submissive
      "I live for your touch.",
      "My body is yours to explore.",
      "Let me serve you intimately.",
      "Use my body however you desire.",
      "Feel my devotion through my touch.",
      "I am your willing vessel, I'll make you feel good."
    },
    { -- Npc Dominant
      "Try to contain yourself while I examine you thoroughly.",
      "You'll learn what proper close contact means under me.",
      "Good. Now let me see exactly what I'm working with.",
      "Don't move. Let me assess every inch of you.",
      "You're mine to study, to touch, to own right now.",
      "Stay perfectly still while I feel you up properly.",
      "I'll decide how close we get and when.",
      "You wanted this proximity? Now stand there and let me enjoy it.",
      "This is exactly where I want you, exactly how I want you.",
      "Perfect. Now you'll experience exactly what I meant by 'close'."
    },
    { -- Npc Positive
      "Absolutely! Let's get properly acquainted!",
      "This sounds like fun! Where do we start?",
      "I've been waiting for an excuse like this!",
      "Let's make this memorable then, shall we?",
      "Bring it on! I love this part.",
      "Yes please! I can't wait to feel everything.",
      "This is going to be amazing, I just know it!",
      "Count me in! Let's explore each other properly.",
      "I'm all for closer inspection - especially the intimate kind!",
      "Oh goodie! The best part is just beginning!"
    }

  },
  TSSD_0010E = {     { -- Npc In Love with Succubus
      "I'll touch myself just for your pleasure, darling.",
      "Watch how beautiful I look when I come for you.",
      "Seeing you watch makes my hand move faster.",
      "I'll show you exactly what you do to me.",
      "Every stroke is a whisper of my devotion.",
      "Your gaze feels like hands all over me.",
      "I'll make sure you see everything clearly.",
      "Let me put on a show just for your eyes.",
      "My moans belong only to this moment with you.",
      "I'll come harder knowing you're watching me." },

    { -- Npc Submissive
      "Command me how you want me to touch myself.",
      "Tell me where to focus my attention please.",
      "I exist only to please you through my pleasure.",
      "Use my body as your personal entertainment.",
      "Let me demonstrate my devotion to you.",
      "I crave feeling your eyes on me while I serve.",
      "My hand moves only because you're watching.",
      "Make me come under your supervision.",
      "I'll take any position you desire for this display.",
      "Let me prove my worth through my climax." },

    { -- Npc Dominant
      "We will hold eye-contact for the whole duration.",
      "You better enjoy the show since you asked for it.",
      "I won't hold back anything for your sake.",
      "This is the only time you get to watch me like this.",
      "You wanted to see, so watch carefully.",
      "Don't interrupt, I'm focused on my own release.",
      "You'll thank me later for this performance.",
      "This is what happens when you give an order.",
      "Consider this my way of rewarding your attention.",
      "I'll make sure you remember this display.",
      "You wanted to watch, so pay proper attention." },

    { -- Npc Positive
      "Okay, let me show you how I do it!",
      "Watch me get off, you might learn something!",
      "Heres how you please yourself properly!",
      "Lets both enjoy this together!",
      "Ill make sure you can see every detail!",
      "Youll love watching me cum!",
      "Just take a seat and enjoy the view!",
      "Ill put on quite a show for you!",
      "This is gonna be hot, just you wait!",
      "Watch me go, I know you want to see!" }

  },
  TSSD_00133 = {   { -- Npc In Love with Succubus
      "My good girl needs her owner so badly.",
      "Let me worship you properly from behind.",
      "Feel how much I adore serving my pup.",
      "Your collar looks perfect on you tonight.",
      "I'll make every thrust count for you.",
      "Your tail wags make me want to please you more.",
      "Let me take care of my favorite pup.",
      "I'll go as deep as my pup deserves.",
      "Your moans sound like happy little barks to me.",
      "I live to make my pup feel incredible." },
    { -- Npc Submissive but still the active part
      "Can we wear matching collars?",
      "Bark for me again, let me hear you!",
      "Yes, fuck your good girl!",
      "Use me however you want!",
      "I need to be your perfect pup!",
      "I'm all yours to mount upon!" },

    { -- Npc Dominant
      "You wanted to play doggy, here's your reward.",
      "Hold still while I fuck my property.",
      "Good girls stay on their hands and knees.",
      "I'll show you how proper dogs get treated.",
      "You don't speak during this, you pant.",
      "Take every inch or I'll punish you.",
      "Your collar means you belong to me tonight.",
      "Try to move and you'll regret it.",
      "This is what happens to dogs who bark.",
      "I own this pup completely right now." },

    { -- Npc Positive
      "Doggie style coming right up!",
      "Ill mount you so good!",
      "Fucking my favorite pup!",
      "You're gonna love this!",
      "Watch me ride you puppy!",
      "Your tail looks amazing back there!",
      "Let me feel that collar!",
      "Just stay on all fours!",
      "Ill make sure you enjoy it!" } },
  TSSD_00139 = { { -- Npc In Love with Succubus
    "Oh my darling, watching you pleasure yourself is the most beautiful sight I've ever seen.",
    "Every gasp, every movement of your hand - it sends thrills straight through my heart.",
    "Please let me see you completely lost in your own pleasure, it drives me wild.",
    "The way your body arches when you touch yourself makes me want to memorize every detail.",
    "Watching you come undone is like watching a masterpiece being created before my eyes.",
    "I could spend eternity just observing the ecstasy on your face when you're like this.",
    "Seeing you so free and uninhibited makes me love you even more deeply.",
    "Hearing those soft moans and sighs while you touch yourself is pure torture in the best way.",
    "Your pleasure is my greatest joy, and watching you take it feels like receiving the rarest gift.",
    "I'll never tire of seeing you surrender completely to your own desires while I watch." },

    { -- Npc Submissive
      "Watching you pleasure yourself is my highest privilege and deepest desire.",
      "Every stroke of your hand fills me with purpose and devotion to your pleasure.",
      "I exist to witness your ecstasy, to absorb every gasp and tremble as my sacred duty.",
      "The sight of you lost in your own body makes me ache with admiration and longing.",
      "Please let me be your audience, let me drink in the spectacle of your perfection.",
      "Seeing you so utterly consumed by pleasure gives me strength beyond words.",
      "Your moans are the sweetest music, your movements the most divine dance I could ever behold.",
      "The way your body responds to your own touch is the most beautiful thing I've ever witnessed.",
      "I will treasure every second of watching you come undone before my eyes.",
      "Your pleasure is my purpose, and seeing you take it is the greatest honor I could imagine." },

    { -- Npc Dominant
      "Very well. This is how a true creature of desire expresses itself.",
      "Fantasize about me whipping you!",
      "I command you to show me everything - leave nothing hidden from my view.",
      "This display should be meticulous and controlled - don't disappoint me.",
      "Let me see every detail of your self-pleasure, every reaction, every sound.",
      "Make sure you maintain perfect eye contact while you work yourself over.",
      "I want to see exactly how my presence affects your ability to please yourself.",
      "Control yourself perfectly - I'll know if you're faking anything.",
      "And now continue - I'm analyzing every aspect of your performance closely.",
      "Remember who is granting this privilege - don't get too lost in yourself." },

    { -- Npc Positive
      "Oh yes, absolutely! Watching you pleasure yourself is going to be so much fun!",
      "I love seeing you completely free and uninhibited like this!",
      "The way you move when you're touching yourself is absolutely mesmerizing.",
      "Every little gasp and moan just makes me want to watch even closer!",
      "Your pleasure looks so good when you're doing it all by yourself.",
      "Hearing those sounds you make while you're working yourself up is incredibly hot.",
      "Seeing you so totally focused on your own body is such a turn-on.",
      "The expressions on your face when you're close are priceless!",
      "Watching you come undone like this is one of my favorite things ever.",
      "Please let me enjoy every second of this beautiful sight with you." }
  },
  TSSD_0013D = { { -- Npc In Love with Succubus
    "Please, yes, take them, they're yours, always yours.",
    "Your mouth feels like heaven on my skin, don't stop.",
    "Feel how hard my nipples get just for your touch.",
    "Taste me, bite me, make them yours completely.",
    "Every suck makes my heart race for you only.",
    "Suck harder, please, mark them as yours forever.",
    "Your devotion is intoxicating, taste my passion.",
    "Work them until I can't think straight anymore.",
    "Yes, oh yes, make them swell with your attention.",
    "My body belongs to your mouth completely."
  },
    { -- Npc Submissive
      "Use my tits however you wish, they exist for you.",
      "Claim them, they belong to your pleasure now.",
      "Feel free to devour them completely if you need to.",
      "Bite harder, show me who owns these breasts.",
      "Worship them properly, drain them dry for me.",
      "Mark them with your love, leave them aching.",
      "Take what you need from them, use them fully.",
      "Taste my submission in every suck of my nipples.",
      "Only your mouth can give these breasts true purpose.",
      "Suck them until I forget my own name, please."
    },
    { -- Npc Dominant
      "Good, now show me you can handle breasts properly.",
      "Keep those pretty lips working until I say stop.",
      "Prove you're worthy of this fine pair by making me moan.",
      "Don't just suck - worship them like you mean it.",
      "Better not disappoint me pet.",
      "Use your tongue properly or we'll be doing this again.",
      "Deeper sucks now, make my nipples feel your devotion.",
      "Work those tits like they're the last thing on Nirn.",
      "Make my breasts feel like they're the only things worth living for right now."
    },
    { -- Npc Positive
      "Bring it on! Give my tits some proper attention!",
      "Oh fuck yes, get that beautiful mouth around my nipples!",
      "This is going to be amazing, I can already tell!",
      "You want to taste them? Have at it, darling!",
      "I knew you could give the best breast treatment, don't let me down!",
      "Yes, work those tits like a pro, make me lose my mind!",
      "Suck hard, bite gently, make me come so hard!",
      "Fuck yes, your mouth seems magical on my sensitive skin!",
      "Take them all in, fill your mouth with my softness.",
      "Deeper, take more, I want you to really feel me."
    } },
  TSSD_00142 = { { -- Npc In Love with Succubus
    "Oh my sweet sin, I'd love to show you just how deep my control can go.",
    "Wrap yourself in my power, darling - I want to feel you surrender completely.",
    "Yes, let me weave my magic through your mind until you're trembling with desire for me.",
    "Feel the threads of my will binding you, making every nerve ending scream my name.",
    "I'll make your pleasure my own creation, shaping every gasp and moan with my touch.",
    "Let me be the architect of your ecstasy, building it higher and tighter with each spell.",
    "Your mind is my canvas tonight, let me paint you with pure sensation.",
    "Trust my control, sweetheart - I'll take you places you've only dreamed of.",
    "Feel how effortlessly I unravel your thoughts, replacing them with devotion for me.",
    "Your pleasure belongs to me now, and I'm going to use it perfectly." },

    { -- Npc Submissive (Pleasure Amplifier)
      "Use my power however you need to feel good, mistress.",
      "The stronger my control over you, the better it feels for me too.",
      "Feel how my magic enhances every touch, every sensation for you.",
      "Your pleasure flows through me like a current, making this so much sweeter.",
      "The tighter I bind your mind, the deeper your moans get for me.",
      "Every spell I cast makes your body sing with intensity just for me.",
      "Your ecstasy is my devotion, and I'll amplify it endlessly.",
      "Watching you lose yourself under my spells fills me with delicious purpose.",
      "My control is your greatest pleasure, and I'll make sure you feel it completely.",
      "The more I dominate your mind, the more perfect you feel against me." },

    { -- Npc Dominant
      "Excellent question. Let me demonstrate exactly what special training entails.",
      "Good. Now close your eyes and let me reshape your awareness properly.",
      "You asked for this, so brace yourself - I'm going deep.",
      "Watch closely as my magic rewires your perception of pleasure.",
      "This isn't just training, this is a masterclass in submission.",
      "Prepare to be thoroughly dominated, starting with that pretty little mind.",
      "I'll adjust your senses until only my voice and my touch exist for you.",
      "You won't remember anything but my name and my hands on you.",
      "Consider this your final lesson in surrendering completely.",
      "And now we begin your true education in how to please me perfectly." },

    { -- Npc Positive
      "Absolutely! This will be so much fun - watch how good it feels!",
      "Oh yes, special training time! Let me show you just how amazing this can be!",
      "I've been waiting for this moment! Get ready to lose yourself in bliss.",
      "This is going to feel incredible - trust me completely.",
      "Let's make tonight unforgettable through your pleasure!",
      "You're in for such a treat when I start weaving my magic through you.",
      "Get comfortable, sweetheart - we're about to take things to new heights!",
      "I promise you'll never experience anything like my special brand of training!",
      "Your body and mind are about to thank you profusely for this decision.",
      "Oh yes, yes, yes - this is going to be perfect in every way possible!",
      "Yes, keep coming back for it!",
      "You always love it!",
      "You are the most obedient student I ever had!" }
  },
  TSSD_00155 = { { -- Npc In Love with Succubus
    "Of course my darling, I want to savor every moment with you properly.",
    "Rest here with me, let me just feel your warmth against me while we wait.",
    "Your concern is so sweet - I'd love nothing more than to relax in your arms.",
    "Tell me stories while we rest, make the waiting time feel precious.",
    "Wrap me up in your affection, help me recharge with your loving presence.",
    "I feel safer and more loved waiting with you than I ever do alone.",
    "Your patience makes my heart flutter - let's enjoy this quiet time together.",
    "Hold me close while we wait, make me feel completely cherished during this break.",
    "I adore how you think of my well-being first, let me melt into your care.",
    "The best part of resting is knowing I'll wake up right beside you." },

    { -- Npc Submissive
      "Yes, mistress allows me to rest only when she commands it.",
      "I'll gladly wait as long as you require, my purpose is your pleasure.",
      "Thank you for permitting me this small comfort, I'll savor it properly.",
      "My body aches delightfully from our last session, let me recover under your watchful gaze.",
      "I exist to serve your needs perfectly, so I'll rest until you say I'm ready again.",
      "Please, keep me close while I recharge, I crave your proximity even in stillness.",
      "The thought of pleasing you better after this rest fills me with anticipation.",
      "I'll count the seconds until you're ready to use me again completely.",
      "Your command to wait gives me purpose, I'll make sure to be at my best for you.",
      "This pause is a gift you're granting me, and I'll accept it with proper gratitude." },

    { -- Npc Dominant
      "Good, we both need this break before continuing properly.",
      "Rest well now - when we resume, I expect complete focus from you.",
      "This pause is strategic, don't mistake it for weakness.",
      "I'll be monitoring your recovery closely, be ready when I tell you.",
      "Sleep if needed, but don't waste this time entirely - reflect on how to please me better.",
      "You should thank me for allowing this respite before your next lesson.",
      "I'll expect perfect performance after this rest, so make sure to recover properly.",
      "This isn't indulgence, it's preparation - don't disappoint me when we continue.",
      "Consider this your final preparation before your true test begins.",
      "And now you'll wait patiently until I say you're ready to serve me again." },

    { -- Npc Positive
      "Oh yes, let's take a little breather and enjoy the moment!",
      "Perfect idea! We can just cuddle up and recharge together.",
      "This waiting time is going to feel so cozy with you beside me.",
      "I love how thoughtful you are - resting with you sounds amazing right now.",
      "Let's make this break special, just enjoying each other's company.",
      "Snuggle up close, this pause is going to be wonderful with you.",
      "The best part is knowing we'll be even more amazing when we continue.",
      "Can't think of anything better than relaxing in your arms like this.",
      "This feels so good already - thank you for suggesting it!",
      "I'm going to treasure every second of this peaceful time with you." }
  },
  TSSD_0015B = {
    { -- Npc In Love with Succubus
      "Oh please, yes! My dick is yours, take it all.",
      "I've been dreaming of your lips on me like this forever.",
      "Feel how hard I am just for you, just for your touch.",
      "Your mouth feels perfect wrapped around me, please don't stop.",
      "Every suck, every lick makes my heart race for you.",
      "Taste me, take me deep, show me how much you crave me.",
      "Yes, oh yes, work my cock just like that, make me feel you need it.",
      "I belong in your mouth, please, take me deeper.",
      "Your devotion is intoxicating, suck me until I come just for you.",
      "Every inch of my cock remembers being worshipped by you."
    },
    { -- Npc Submissive
      "Yes! Use my cock however you wish.",
      "It's yours to claim, please take what you need from me.",
      "Feel how ready I am for your service.",
      "My body exists to please you, take my pleasure with your mouth.",
      "Work me until I break for you, use me completely.",
      "My cock is yours to devour, please make me serve you properly.",
      "Let me feel your dominance through my cock.",
      "Take everything, drain me dry with your perfect lips.",
      "Only your mouth can give me the release I crave so desperately."
    },
    { -- Npc Dominant
      "Good. Now show me you can handle it properly.",
      "Keep those pretty lips working until I say stop.",
      "Prove you're worthy of my cock, make me come harder than anyone ever has.",
      "Don't just suck - worship it. Make me believe you mean it.",
      "I'll judge your technique right here in this moment.",
      "Better not disappoint me pet.",
      "Use your tongue properly, or we'll be doing this again.",
      "Deeper. Wider. Show me what that talented mouth can do.",
      "Make my cock feel like it's the only thing worth living for right now."
    },
    { -- Npc Positive
      "Bring it on! Drain me dry!",
      "Oh fuck yes, get that beautiful mouth around me!",
      "This is going to be amazing, I can already tell!",
      "You want to taste me? Have at it, darling!",
      "I knew you could give the best head, don't let me down!",
      "Yes, work that cock like a pro, make me lose my mind!",
      "Suck hard, take me deeper, make me come so hard!",
      "Fuck yes, your mouth seems magical!"
    } }


}

local function get_thrall_type(pSpeaker_id)
  local thrallDomFaction = get_formid(0x00090, "TintsOfASuccubusSecretDesires.esp")
  local thrallSubFaction = get_formid(0x000A8, "TintsOfASuccubusSecretDesires.esp")
  local thrallNotAThrall = get_formid(0x0008F, "TintsOfASuccubusSecretDesires.esp")
  local thrallType = 1
  if is_in_faction(pSpeaker_id, thrallSubFaction) == 1 then
    thrallType = 2
  end
  if is_in_faction(pSpeaker_id, thrallDomFaction) == 1 then
    thrallType = 3
  end
  if is_in_faction(pSpeaker_id, thrallNotAThrall) == 0 then
    thrallType = 4
  end
  if is_in_faction(pSpeaker_id, thrallNotAThrall) == 0 and get_relationship_rank(speaker_id, target_id) == 4 and math.random() < 0.5 then
    thrallType = 1
  end
  return thrallType
end

function replace(text)
  local pool = pools[text]
  if pool then
    log_info(text)
    local thrallType = get_thrall_type(speaker_id)
    send_mod_event("TSSD_DialogueFinished", text, 0.0, speaker_id)
    local nxtText
    if #pool == 1 then
      nxtText = pool[1][math.random(1, #pool[1])]
    else
      nxtText = pool[thrallType][math.random(1, #pool[thrallType])]
    end

    log_info(nxtText)
    return nxtText
  end
  return text
end
